# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 06e30d75b017c3019f81bbe6d2a003c8786e7649119491038fc17c4410932f7d8769bec9914be0418cdadfc82e8b9388d2e40b6c73531da9f59f2784bb474a27

test:
  secret_key_base: 72f08a57fcad281322ebeb897c30117eae88707b2c2a709309707d81b4901185cb990043b914915374bc96ae79693965601a622bfc8407ee5326f70465f05cf2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
